sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t ferranlao/react-test -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true ferranlao/react-test npm test

after_success:
  - docker build -t ferranlao/multi-client ./client
  - docker build -t ferranlao/multi-nginx ./nginx
  - docker build -t ferranlao/multi-server ./server
  - docker build -t ferranlao/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ferranlao/multi-client
  - docker push ferranlao/multi-nginx
  - docker push ferranlao/multi-server
  - docker push ferranlao/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-729020405857
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY